Core2Hastane/Models/ErrorViewModel.cs
using System;

namespace Core2Hastane.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core2Hastane/Controllers/DoktorlarController.cs
using Core2Hastane.Data;
using Core2Hastane.model;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Core2Hastane.Controllers
{
    public class DoktorlarController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DoktorlarController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var listele = _db.Doktorlar.ToList();
            return View(listele);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Doktorlar doktorlar)
        {
            _db.Doktorlar.Add(doktorlar);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var update=_db.Doktorlar.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(Doktorlar doktorlar)
        {
            _db.Update(doktorlar);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var delete = _db.Doktorlar.Find(id);
            _db.Doktorlar.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Core2Hastane/Controllers/HastalarController.cs
using Core2Hastane.Data;
using Core2Hastane.model;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Core2Hastane.Controllers
{
    public class HastalarController : Controller
    {
        private readonly ApplicationDbContext _db;
        public HastalarController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var listele = _db.Hastalar.ToList();
            return View(listele);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Hastalar hastalar)
        {
            _db.Hastalar.Add(hastalar);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var update = _db.Hastalar.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(Hastalar hastalar)
        {
            _db.Update(hastalar);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var delete = _db.Hastalar.Find(id);
            _db.Hastalar.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Core2Hastane/Controllers/HomeController.cs
using Core2Hastane.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Core2Hastane.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Core2Hastane/Controllers/PolikliniklerController.cs
using Core2Hastane.Data;
using Core2Hastane.model;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Core2Hastane.Controllers
{
    public class PolikliniklerController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PolikliniklerController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var listele = _db.Poliklinikler.ToList();
            return View(listele);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Poliklinikler poliklinikler)
        {
            _db.Poliklinikler.Add(poliklinikler);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var update = _db.Poliklinikler.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(Poliklinikler poliklinikler)
        {
            _db.Update(poliklinikler);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var delete = _db.Poliklinikler.Find(id);
            _db.Poliklinikler.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Core2Hastane/Controllers/RandevularController.cs
using Core2Hastane.Data;
using Core2Hastane.model;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Core2Hastane.Controllers
{
    public class RandevularController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RandevularController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var listele = _db.Randevular.ToList();
            return View(listele);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Randevular randevular)
        {
            _db.Randevular.Add(randevular);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var update = _db.Randevular.Find(id);
            return View(update);
        }
        [HttpPost]
        public IActionResult Edit(Randevular randevular)
        {
            _db.Update(randevular);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var delete = _db.Randevular.Find(id);
            _db.Randevular.Remove(delete);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Core2Hastane/Controllers/SiteController.cs
using Microsoft.AspNetCore.Mvc;

namespace Core2Hastane.Controllers
{
    public class SiteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult InnerPage()
        {
            return View();
        }

    }
}

Core2Hastane/Views/Doktorlar/Create.cshtml
@model Core2Hastane.model.Doktorlar

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Doktorlar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unvan" class="control-label"></label>
                <input asp-for="Unvan" class="form-control" />
                <span asp-validation-for="Unvan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuId" class="control-label"></label>
                <select asp-for="RandevuId" class ="form-control" asp-items="ViewBag.RandevuId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Doktorlar/Edit.cshtml
@model Core2Hastane.model.Doktorlar

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Doktorlar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DoktorId" />
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unvan" class="control-label"></label>
                <input asp-for="Unvan" class="form-control" />
                <span asp-validation-for="Unvan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuId" class="control-label"></label>
                <select asp-for="RandevuId" class="form-control" asp-items="ViewBag.RandevuId"></select>
                <span asp-validation-for="RandevuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>
@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

Core2Hastane/Views/Doktorlar/Index.cshtml
@model IEnumerable<Core2Hastane.model.Doktorlar>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Yeni Doktor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DoktorAdSoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unvan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Randevular)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoktorAdSoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unvan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Randevular.HastaAdiSoyadi)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DoktorId">Edit</a> |
               
                <a asp-action="Delete" asp-route-id="@item.DoktorId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Core2Hastane/Views/Hastalar/Create.cshtml
@model Core2Hastane.model.Hastalar

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Hastalar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HastaAdiSoyadi" class="control-label"></label>
                <input asp-for="HastaAdiSoyadi" class="form-control" />
                <span asp-validation-for="HastaAdiSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HastaTC" class="control-label"></label>
                <input asp-for="HastaTC" class="form-control" />
                <span asp-validation-for="HastaTC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HastaDT" class="control-label"></label>
                <input asp-for="HastaDT" class="form-control" />
                <span asp-validation-for="HastaDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuId" class="control-label"></label>
                <select asp-for="RandevuId" class ="form-control" asp-items="ViewBag.RandevuId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Hastalar/Edit.cshtml
@model Core2Hastane.model.Hastalar

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Hastalar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HastaId" />
            <div class="form-group">
                <label asp-for="HastaAdiSoyadi" class="control-label"></label>
                <input asp-for="HastaAdiSoyadi" class="form-control" />
                <span asp-validation-for="HastaAdiSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HastaTC" class="control-label"></label>
                <input asp-for="HastaTC" class="form-control" />
                <span asp-validation-for="HastaTC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HastaDT" class="control-label"></label>
                <input asp-for="HastaDT" class="form-control" />
                <span asp-validation-for="HastaDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuId" class="control-label"></label>
                <select asp-for="RandevuId" class="form-control" asp-items="ViewBag.RandevuId"></select>
                <span asp-validation-for="RandevuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Hastalar/Index.cshtml
@model IEnumerable<Core2Hastane.model.Hastalar>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Yeni Hasta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HastaAdiSoyadi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HastaTC)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HastaDT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Randevular)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HastaAdiSoyadi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HastaTC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HastaDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Randevular.HastaAdiSoyadi)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.HastaId">Edit</a> |
               
                <a asp-action="Delete" asp-route-id="@item.HastaId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Core2Hastane/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Core2Hastane/Views/Poliklinikler/Create.cshtml
@model Core2Hastane.model.Poliklinikler

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Poliklinikler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BolumAdi" class="control-label"></label>
                <input asp-for="BolumAdi" class="form-control" />
                <span asp-validation-for="BolumAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorId" class="control-label"></label>
                <select asp-for="DoktorId" class ="form-control" asp-items="ViewBag.DoktorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Poliklinikler/Edit.cshtml
@model Core2Hastane.model.Poliklinikler

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Poliklinikler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BolumId" />
            <div class="form-group">
                <label asp-for="BolumAdi" class="control-label"></label>
                <input asp-for="BolumAdi" class="form-control" />
                <span asp-validation-for="BolumAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorId" class="control-label"></label>
                <select asp-for="DoktorId" class="form-control" asp-items="ViewBag.DoktorId"></select>
                <span asp-validation-for="DoktorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Poliklinikler/Index.cshtml
@model IEnumerable<Core2Hastane.model.Poliklinikler>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Yeni Poliklinik</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BolumAdi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoktorAdSoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doktorlar)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BolumAdi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoktorAdSoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doktorlar.DoktorAdSoyad)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BolumId">Edit</a> |
              
                <a asp-action="Delete" asp-route-id="@item.BolumId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Core2Hastane/Views/Randevular/Create.cshtml
@model Core2Hastane.model.Randevular

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Randevular</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HastaAdiSoyadi" class="control-label"></label>
                <input asp-for="HastaAdiSoyadi" class="form-control" />
                <span asp-validation-for="HastaAdiSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BolumAdi" class="control-label"></label>
                <input asp-for="BolumAdi" class="form-control" />
                <span asp-validation-for="BolumAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuTarihi" class="control-label"></label>
                <input asp-for="RandevuTarihi" class="form-control" />
                <span asp-validation-for="RandevuTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuSaati" class="control-label"></label>
                <input asp-for="RandevuSaati" class="form-control" />
                <span asp-validation-for="RandevuSaati" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Randevular/Edit.cshtml
@model Core2Hastane.model.Randevular

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Randevular</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RandevuId" />
            <div class="form-group">
                <label asp-for="HastaAdiSoyadi" class="control-label"></label>
                <input asp-for="HastaAdiSoyadi" class="form-control" />
                <span asp-validation-for="HastaAdiSoyadi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BolumAdi" class="control-label"></label>
                <input asp-for="BolumAdi" class="form-control" />
                <span asp-validation-for="BolumAdi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoktorAdSoyad" class="control-label"></label>
                <input asp-for="DoktorAdSoyad" class="form-control" />
                <span asp-validation-for="DoktorAdSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuTarihi" class="control-label"></label>
                <input asp-for="RandevuTarihi" class="form-control" />
                <span asp-validation-for="RandevuTarihi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RandevuSaati" class="control-label"></label>
                <input asp-for="RandevuSaati" class="form-control" />
                <span asp-validation-for="RandevuSaati" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Dön</a>
</div>
@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

Core2Hastane/Views/Shared/LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Bare - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/admintema/assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    
    <link href="~/admintema/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Medicana Admin Panel</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Site")">Anasayfa</a></li>
            
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody();
    <!-- Page content-->
  @*  <div class="container">
        <div class="text-center mt-5">
            <h1>A Bootstrap 5 Starter Template</h1>
            <p class="lead">A complete project boilerplate built with Bootstrap</p>
            <p>Bootstrap v5.2.3</p>
        </div>
    </div>*@
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/admintema/js/scripts.js"></script>
</body>
</html>